version: '3'

services:
  flask:
    build: flask/
    ports: 
      - 5001:5001
    networks:
      - deploy_network
    container_name: flask

  streamlit:
    build: streamlit/
    depends_on:
      - flask
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge